---
dependencies:
  # infinidb_common responsible for shared vars of infinidb
  - { role: infinidb_common }
  - { role: python_package, python_packages: ['supervisor'] }
  - role: system_directory
    system_directories:
      - directory: "{{ infinidb_supervisor_script | dirname }}"