# python-setuptools setup as a role dependency
# Make sure pip available
- name: Ensure pip is present (easy_install)
  easy_install: name=pip 
  when: python_packages is defined

# Install python packages
- name: Ensure python libraries are present (pip)
  pip: name={{ item }} state=present
  with_items: python_packages
  when: python_packages is defined