# Create symlinks for system
- name: Ensure symlinks and ownership for install
  file: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner | default(omit) }} group={{ item.group | default(omit) }} state=link
  with_items: system_symlinks